version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: olympsearch-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: olympsearch
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d olympsearch"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: olympsearch-api
    restart: unless-stopped
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env          # ← будет читать наш .env (создадим на следующем шаге)

volumes:
  pgdata: